// <auto-generated />
namespace TopGym_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ثيهفحقخؤثيعقث : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ثيهفحقخؤثيعقث));
        
        string IMigrationMetadata.Id
        {
            get { return "202209081147468_ثيهفحقخؤثيعقث"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
